### ISSUE TITLE
OBSERVACIONES PARA CORRECCIÓN 14-04-2024

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#33]
[OBSERVACIONES PARA CORRECCION 14-04-2024.docx](https://github.com/V3ct0r/Autosoft/files/15210215/OBSERVACIONES.PARA.CORRECCION.14-04-2024.docx)

De este Documento esta pendiente solo la corrección para muestre la tasa con los 4 decimales en la ventana de Accesorios/Cargos.

![CORREGIR TASA FORMA ACCESORIOS-CARGOS 04-05-2024 11-35-01 a-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/38afebfe-de65-4a27-ab32-71429c7cf19e)

Verifica esto Hector y me comentas

RECUERDA SIEMPE MOSTRAR EN SYSCAR LA TASA CON LOS 4 DECIMALES

**Comment by V3ct0r** [comment]
Ya lo estoy haciendo

**Comment by V3ct0r** [comment]
Listo, En Vehículos en inventario también esta puesto la **Tasa**

con los 4 decimales?

**Comment by ptillero** [comment]
Recuerda siempre mostrar en Syscar la tasa de cambio con 4 decimales...

No entiedo lo de los emoils ajajajajaj

**Comment by V3ct0r** [comment]
> Recuerda siempre mostrar en Syscar la tasa de cambio con 4 decimales...
> 
> No entiedo lo de los emoils ajajajajaj

Correcto, lo estoy tomando en cuenta

**Comment by ptillero** [comment]
CORREGIDA
