### ISSUE TITLE
MEJORA FORMA VEHICULO PARA PRESUPUESTO 04-05-24

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#35]
Mejora para la forma de Vehículo para Presupuesto. Reorganización de la presentacion de los datos de Precio de Venta , Accesorios y Cargos
![MEJORA FORMA VEHICULO PARA PRESUPUESTO](https://github.com/V3ct0r/Autosoft/assets/94719199/c6166372-a0d0-4754-a60d-6a309899c7fa)

**Comment by V3ct0r** [comment]
De momento solamente he hecho el cambio del campo Tasa, las mejoras visuales si las quiero discutir mejor para estar seguro
