### ISSUE TITLE
ERROR AL EDITAR TASA DE CAMBIO, DEPARTAMENTO Y CENTRO COSTOS COMPRAS VEHICULO

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#36]
Estos errores se presentan al Incluir o Modificar una compra de Vehículo.
![ERROR DEPARTAMENTO Y CENTRO DE COSTOS COMPRAS VEHICULO 04-05-2024 07-03-49 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/e20b8fdb-00f3-43c4-95a0-e31e7700aa41)

**Comment by V3ct0r** [comment]
Listo

**Comment by ptillero** [comment]
Se corrigieron los errores que se presentaban al editar el departamento, tasa y centro de costo,
pero al intentar grabar la compra se muestra un error null haciendo referencia al campo NUMDOCAFE de la tabla ADMOVPAG
![ERROR AL INTENTAR GRABAR UNA MODIFICACION EN COMPRA DE VEHICULO 05-05-2024 10-26-47 a-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/7664a257-5c5c-41f3-aed9-5c5becc5e110)

**Comment by V3ct0r** [comment]
En varias partes del código de **Compras** no estaba guardando ningún valor en el campo NUMDOCAFE, ya hice las respectivas modificaciones pero aun no lo he probado.

Hector, referente a este punto la versión que tengo activa en el concesionario fue compilada el 16-04-2024 08:18pm, esta operando normalmente grabando las compras de vehículos. Lo que quiere decir que algo se omitió o se modificaron  los dataset, porque

**Comment by V3ct0r** [comment]
Ya la sección de Vehículos (cuando esta en Compras) ya esta terminada, pero falta revisar. Cuando quise guardar la compra de unos errores pero es con lo de las formas de pago, esa parte todavía no la he terminado

**Comment by ptillero** [comment]
LOS TRES ERRORES FUERON CORREGIDAS EN LA VERSIÓN DEL 10-05-2024

**Comment by ptillero** [comment]
INCIDENCIA FINALIZADA
