### ISSUE TITLE
ERROR AL INCLUIR VEHICULO DESDE COMPRA 04-05-2024 07-32-54 p-m-

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#37]
ERROR Y OBSERVACIONES AL INCLUIR VEHÍCULO DESDE COMPRA 04-05-2024 07-32-54 p-m-
![ERROR AL INCLUIR VEHICULO DESDE COMPRA 04-05-2024 07-32-54 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/c62704b6-020a-43d6-bae8-03d8f7a20138)

**Comment by ptillero** [comment]
SOLVENTADO EL ERROR DE LA TASAME

**Comment by ptillero** [comment]
LOS OTROS DOS PUNTOS SIGUEN PENDIENTES

![VEHICULO EN INVENTARIO 13-05-2024 01-21-35 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/d92f3b21-0af1-4f44-aad1-9bbd13dd977d)

**Comment by V3ct0r** [comment]
Listo, falta por revisar

**Comment by ptillero** [comment]
INCIDENCIA FINALIZADA
