### ISSUE TITLE
NO ACTUALIZA LOS PRECIOS EN MONEDA NACIONAL EN VEHICULOS PARA PRESUPUESTOS

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#42]
![NO ACTUALIZA PRECIO MONEDA NACIONAL01-06-2024 01-43-05 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/39bc3dd6-437d-4633-95f2-4b6297ea1442)

**Comment by V3ct0r** [comment]
Listo, falta por revisar

**Comment by ptillero** [comment]
Ya se actualiza los precios en Moneda Nacional, pero observe un detalle con el calculo del descuento y la totalización del Precio Total.
![CALCULO PRECIO TOTAL Y DESCUENTO EN VEHICULOS PARA PRESUPUESTOS 03-06-2024 08-30-37 a-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/3b2473d3-5bf3-430c-a310-8595a8bbe26f)

**Comment by ptillero** [comment]
NO TOTALIZA EN ALGUNOS CASOS 
![NO TOTALIZA LOS ACCESORIOS Y CARGOS EN VEHICULO PARA PRESUPUESTO 03-06-2024 10-29-44 a-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/74bcc90a-59f4-4f94-919e-64f268d27424)
LOS ACCESORIOS Y CARGOS EN VEHÍCULO PARA PRESUPUESTO 03-06-2024 10-29-44 a-m-

**Comment by V3ct0r** [comment]
De todo lo que me has pasado de esta incidencia ya esta listo, falta por revisar

**Comment by V3ct0r** [comment]
Antes de guardar coloque las siguiente comprobaciones

* Precio  sea mayor que cero.
* Porcentaje de descuento  sea mayor que cero.
* Descuento sea mayor que cero.
* Porcentaje de descuento no sea mayor que cien.
* Descuento no sea mayor que el Precio.

**Comment by ptillero** [comment]
CORREGIDA
