### ISSUE TITLE
MSG CANNOT FOCUS EN PRESUPUESTO DE VEHICULO 01-06-2024 12-35-20 p-m-

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#43]
![MSG CANNOT FOCUS EN PRESUPUESTO DE VEHICULO01-06-2024 12-35-20 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/b244c92b-98bd-461e-8697-fcffb0b7cd65)

**Comment by V3ct0r** [comment]
Listo, falta por revisar

**Comment by ptillero** [comment]
CORREGIDO
