### ISSUE TITLE
GASCOB NULL AL GRABAR PRESUPUESTO 01-06-2024 01-35-03 p-m-

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#44]
![GASCOB NULL AL GRABAR PRESUPUESTO 01-06-2024 01-35-03 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/576a6cde-6b59-4a62-b077-1cc1616b4779)

**Comment by V3ct0r** [comment]
Listo, falta por revisar

**Comment by V3ct0r** [comment]
Al campo **GASCOB** le asigne cero, ya que de momento no se que valor le voy a asignar

**Comment by ptillero** [comment]
CORREGIDA
