### ISSUE TITLE
En la ficha Vehículo en Inventario permitir modificar el campo SERIAL DE CARROCERIA. Solo permite modificar la Placa y serial de Motor

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#45]
![PERMITIR MODIFICAR SERIAL DE CARROCERIA 01-06-2024 02-45-06 p-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/6b2257c7-b358-4f71-b83f-2e8af0c78c29)

**Comment by V3ct0r** [comment]
Listo, falta por revisar

**Comment by V3ct0r** [comment]
La mayor parte del código de ese campo estaba ahí, pero por algún motivo fue deshabilitado

**Comment by ptillero** [comment]
CORREGIDO
