### ISSUE TITLE
CONSERVAR EL PUNTERO EN EL REGISTRO MODIFICADO Y SE TRASLADE AL PRIMER REGISTRO 03-06-2024 

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#46]
Realizar las Modificaciones necesarias para que luego de Modificar un Stock  en Vehiculo para Presupuesto, conserve en Pantalla el Stock sobre el cual se estaba realizando la Modificacion y no traslade el cursor al Primer Registro.

En vehículo para Presupuesto en el Numero de Stock, cambiar el orden de presentación. Colocarlo en Orden descendente. Debe mostrar al entrar el mayor stock.

![CONSERVAR EL PUNTERO EN EL REGISTRO MODIFICADO Y SE TRASLADE AL PRIMER REGISTRO 03-06-2024 09-18-17 a-m-](https://github.com/V3ct0r/Autosoft/assets/94719199/ef3512e0-b9ee-497b-b96b-31e21a4dfdcb)

**Comment by V3ct0r** [comment]
Listo, falta por revisar 👍🏼
