### ISSUE TITLE
Actualizar el campo IMPORTE2 en la tabla ADFPGCOM

### ISSUE THREAD

**Issue by V3ct0r** [V3ct0r/Autosoft#47]
El campo **IMPORTE2** de la tabla **ADFPGCOM** se esta guardando en 0 cuando es en moneda nacional

**Comment by V3ct0r** [comment]
El código de guardar su valor en el campo **IMORTE2** ya estaba hecho pero no estaba tomando bien el valor y cuando hacia la division el total era 0, en la única forma de pago donde estaba corregido fue en _Pago por Anticipado_ pero una una manera diferente así que fue corregida como debe ser como en todas las de mas formas de pago en todos los proyectos

**Comment by V3ct0r** [comment]
Falta por confirmar

**Comment by V3ct0r** [comment]
Se tuvo que comentar la siguiente linea
```
if (txtImporte.Text <> '') then
    txtImporte.EditValue := txtImporte.Text;
``` 
del procedimiento **BtnGuardar** de todas las formas de pagos actualizadas porque estaba haciendo que guardara el valor como si se tratara de una cadena y no como un valor de tipo Double

**Comment by V3ct0r** [comment]
Acabo de terminar los respectivos ajustes a las formas de pagos del proyecto de **Servicio**

**Comment by ptillero** [comment]
CORREJIDO

**Comment by ptillero** [comment]
PROPUESTA CORREGIDA
