### ISSUE TITLE
MEJORA EN LA VISTA FACTURA ORDEN DE REPARACION (SERVICIO)

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#53]
A ESTA VISTA SE LE DEBE AGREGAR LA COLUMNA KILOMETRAJE DE ENTRADA  Y QUITAR LA COLUMNA REGIMEN.
TAMBIRN DEBE PERMITIR MODIFICAR EL ANCHO DE LAS COLUMNAS, DE MANERA DE PODER AJUSTARLAS PARA EFECTOS DEL REPORTE.

VER SI ESTE TIPO DE MAYA TIENE LA OPCION DE PERMITIR EXPANDER Y CONTRAER LAS FILAS, ASI COMO LO REALIZA EL PIVOT.

EN LA IMAGEN DEJO ILUSTADO LOS COMENTARIOS

![VISTA FACTURA ORDEN DE REPARACION](https://github.com/user-attachments/assets/567aa6a6-d643-4095-af46-45262e27b683)

**Comment by V3ct0r** [comment]
Está propuesta está finalizada

**Comment by V3ct0r** [comment]
Está propuesta está finalizada, falta por revisión
