### ISSUE TITLE
PARAMETROS DE BUSQUEDA LISTADO ORDEN DE REPARACION

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#54]
NECESITO LOS PARAMETROS DE BUSQUEDA DE ESTE REPORTE PARA LA CONFIGURACION DE MISMO.

CAMBIAR LA DESCRIPCION DE ESTA OPCION Y CUALQUIER OTRA DONDE SE ABREVE ORDEN DE REPARACON. POR LO GENERAL SE MUESTRA O/REPARACION, SE DEBE "MOSTRAR ORDEN DE REPARACION". 

TAMBIEN DONDE SE VEA ABREVIADO LA PALABRA TECNICO.

https://github.com/user-attachments/assets/439dd029-0afd-40fb-87c3-e250ed6da275

**Comment by V3ct0r** [comment]
**Reporte**
# Listado de Orden de Reparación
### Gestión: ODR
### Opción: REP
2 txtFechaD
3 txtFechaH
4 cbNumOrdenD
5 cbNumOrdenH
6 cbNumFacD
7 cbNumFacH
8 cxcbFechaFacturaD
9 cxcbFechaFacturaH
10 cxcbFechaEntradaD
11 cxcbFechaEntradaH
12 cxcbFechaListaD
13 cxcbFechaListaH
14 cbPlacaD
15 cbPlacaH
16 cbCliD
17 cbCliH
18 cbCodCajD
19 cbCodCajH 0-Contado 1-Credito 2-Giros
20 cxConPagD
21 cxConPagH
22 cbFormaPagD CB CH DP EF TA
23 cbFormaPagH
24 cbTipoOdenD
25 cbTipoOdenH
26 txtSerial
27 cbEstatus

**Comment by V3ct0r** [comment]
**Reporte**
# Historial de entrada de vehículo
### Gestión: HFS
### Opción: REP
0 CbCliD
1 CbCliH
2 CbPlacaD
3 CbPlacaH
4 CbModeloD
5 CbModeloH
6 CbAsesorD
7 CbAsesorH
8 CbSerialD
9 CbSerialH
10 txtNombre
11 txtApellido
12 cxCbFechaFacturaD
13 cxCbFechaFacturaH

**Comment by ptillero** [comment]
COPIADO
