### ISSUE TITLE
DESGLOSE DE ANTICIPOS VEHICULOS.

### ISSUE THREAD

**Issue by ptillero** [V3ct0r/Autosoft#56]
El desglose del anticipo sigue con el problema de no poder modificar los elementos del mismo.

También se esta presentando inconvenientes al tratar de cambiar o asignar un nuevo cliente, el sistema se queda en un ciclo, hay que cerrarlo por el administrador de aplicaciones.

Revisar

**Comment by V3ct0r** [comment]
En la tabla **VHDESANT** se creó una clave primaria con los campos **NUMADE, TIPO, CODREG**

**Comment by V3ct0r** [comment]
Ya está corregido el problema de cuando se quiere modificar un registro no muestra el correcto, internamente se crearon unas claves primarias para que no diera el problema de que tomaba otro valor

**Comment by V3ct0r** [comment]
Tuve algunos detalles al momento de modificar el desglose y eso me retrasó un poco, ahorita ya solucione con el error del DataSet **IBDCliente** con el campo **SALDO**, en una consulta no estaba colocado el campo

**Comment by V3ct0r** [comment]
Propuesta finalizada, falta por revisión

**Comment by ptillero** [comment]
Modificación, probada. Funcionado perfecto
